FROM python:3.7.4-slim-buster

RUN apt-get update
RUN python -m pip install --upgrade pip
RUN python -m pip install Django

WORKDIR /app
COPY . /app

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]