version: '3.1'

services:
  django-app:
    build: 
      context: . #where all the files are located
      dockerfile: Dockerfile.dev #which dockerfile to use
    ports:
      - 8000:8000
    volumes:
      - .:/app
    # command: python manage.py runserver